# ASSIGNMENT : IRIS MULTI-CLASS CLASSIFICATION

###### Purpose :
To predict the species of flower .
###### Description :
The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).
###### Requirements :
1) Code must be in tf 2.0 .

2) Accuracy must be in between 95-97% .

3) Model shouldn't be Overfit (You can add drop out layer for this) .

### STEP 1 : Load all the necessary libraries 

https://www.kaggle.com/ash316/ml-from-scratch-with-iris

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [4]:
import seaborn as sns
import matplotlib.pyplot as plt

### STEP 2 : Data Preparation
This step consists of multiple sub steps from data loading [download](https://github.com/ramsha275/PIAIC-Sir-Anees-Quarter-2/blob/master/Deep%20Learning/iris.csv),shuffling ,spliting in **Train** and **Test** sets to one-hot-enconding on labels . 


In [5]:
encoder = LabelBinarizer()
seed = 42

In [6]:
iris_data_df = pd.read_csv('iris.csv')
iris_data_df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [7]:
iris_data_df_1 = iris_data_df.loc[:, iris_data_df.columns != 'variety']
iris_data_df_1.head()

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [8]:
#pd.DataFrame(np.where(, 1, 0))
#iris_data_df.loc[]
#pd.DataFrame(np.where(iris_data_df['variety'].isin(['Setosa', 'Versicolor','Virginica']), 1, 0))
#iris_data_df['variety'].isin(['Setosa', 'Versicolor','Virginica']
iris_target_df = pd.DataFrame({
    'Setosa' : iris_data_df['variety'] == 'Setosa',
    'Versicolor' : iris_data_df['variety'] == 'Versicolor',
    'Virginica' : iris_data_df['variety'] == 'Virginica',
})*1
iris_target_df.head()

Setosa  Versicolor  Virginica
0       1           0          0
1       1           0          0
2       1           0          0
3       1           0          0
4       1           0          0

In [9]:
X_train,X_test,y_train,y_test = train_test_split(iris_data_df_1,
                                                 iris_target_df,
                                                 test_size=0.30,
                                                 random_state=seed)

In [10]:
scaler = MinMaxScaler(feature_range=(0,1))
scaler

MinMaxScaler(copy=True, feature_range=(0, 1))

In [11]:
X_train = pd.DataFrame(scaler.fit_transform(X_train),
                               columns=X_train.columns,
                               index=X_train.index)
X_train.head()

sepal.length  sepal.width  petal.length  petal.width
81       0.352941     0.181818      0.464286     0.375000
133      0.588235     0.363636      0.714286     0.583333
137      0.617647     0.500000      0.785714     0.708333
75       0.676471     0.454545      0.589286     0.541667
109      0.852941     0.727273      0.892857     1.000000

In [12]:
X_test = pd.DataFrame(scaler.transform(X_test),
                           columns=X_test.columns,
                           index=X_test.index)
X_test.head()

sepal.length  sepal.width  petal.length  petal.width
73       0.529412     0.363636      0.642857     0.458333
18       0.411765     0.818182      0.107143     0.083333
118      1.000000     0.272727      1.035714     0.916667
78       0.500000     0.409091      0.607143     0.583333
76       0.735294     0.363636      0.660714     0.541667

### STEP 3 : Model Architecture 


###### Input : 4 
###### 1 hidden Layer : 8 nodes
###### Output : 3

In [13]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='tanh', name='input_layer'))
model.add(Dense(10, activation='tanh', name='hidden_layer'))
model.add(Dense(3, activation='softmax', name='output_layer'))
model

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


### STEP 4 : Compilation Step 

In [14]:
model.compile(loss="categorical_crossentropy",
                  optimizer="adam",
                  metrics=['accuracy'])
model

<h2>Train The Model</h2>

In [15]:
model.fit(
       X_train,
       y_train,
       epochs=200,
       shuffle=True, # shuffle data randomly.
       #NNs perform best on randomly shuffled data
       verbose=2 # this will tell keras to print more detailed info
       # during trainnig to know what is going on
       )

Epoch 1/200
105/105 - 2s - loss: 1.0853 - acc: 0.3524
Epoch 2/200
105/105 - 0s - loss: 1.0684 - acc: 0.3524
Epoch 3/200
105/105 - 0s - loss: 1.0536 - acc: 0.3619
Epoch 4/200
105/105 - 0s - loss: 1.0379 - acc: 0.3619
Epoch 5/200
105/105 - 0s - loss: 1.0239 - acc: 0.3810
Epoch 6/200
105/105 - 0s - loss: 1.0102 - acc: 0.4000
Epoch 7/200
105/105 - 0s - loss: 0.9965 - acc: 0.5143
Epoch 8/200
105/105 - 0s - loss: 0.9841 - acc: 0.5810
Epoch 9/200
105/105 - 0s - loss: 0.9713 - acc: 0.6286
Epoch 10/200
105/105 - 0s - loss: 0.9590 - acc: 0.6381
Epoch 11/200
105/105 - 0s - loss: 0.9465 - acc: 0.6476
Epoch 12/200
105/105 - 0s - loss: 0.9342 - acc: 0.6476
Epoch 13/200
105/105 - 0s - loss: 0.9229 - acc: 0.6476
Epoch 14/200
105/105 - 0s - loss: 0.9103 - acc: 0.6476
Epoch 15/200
105/105 - 0s - loss: 0.8996 - acc: 0.6476
Epoch 16/200
105/105 - 0s - loss: 0.8874 - acc: 0.6476
Epoch 17/200
105/105 - 0s - loss: 0.8756 - acc: 0.6571
Epoch 18/200
105/105 - 0s - loss: 0.8641 - acc: 0.6571
Epoch 19/200
105/10

Epoch 150/200
105/105 - 0s - loss: 0.2786 - acc: 0.9714
Epoch 151/200
105/105 - 0s - loss: 0.2768 - acc: 0.9714
Epoch 152/200
105/105 - 0s - loss: 0.2743 - acc: 0.9714
Epoch 153/200
105/105 - 0s - loss: 0.2712 - acc: 0.9714
Epoch 154/200
105/105 - 0s - loss: 0.2684 - acc: 0.9619
Epoch 155/200
105/105 - 0s - loss: 0.2662 - acc: 0.9619
Epoch 156/200
105/105 - 0s - loss: 0.2645 - acc: 0.9619
Epoch 157/200
105/105 - 0s - loss: 0.2621 - acc: 0.9619
Epoch 158/200
105/105 - 0s - loss: 0.2590 - acc: 0.9619
Epoch 159/200
105/105 - 0s - loss: 0.2565 - acc: 0.9619
Epoch 160/200
105/105 - 0s - loss: 0.2540 - acc: 0.9619
Epoch 161/200
105/105 - 0s - loss: 0.2520 - acc: 0.9619
Epoch 162/200
105/105 - 0s - loss: 0.2491 - acc: 0.9619
Epoch 163/200
105/105 - 0s - loss: 0.2467 - acc: 0.9619
Epoch 164/200
105/105 - 0s - loss: 0.2451 - acc: 0.9619
Epoch 165/200
105/105 - 0s - loss: 0.2421 - acc: 0.9619
Epoch 166/200
105/105 - 0s - loss: 0.2405 - acc: 0.9714
Epoch 167/200
105/105 - 0s - loss: 0.2384 - acc:

### STEP 5 : Evaluation 

In [17]:
test_error_rate = model.evaluate(X_test, y_test, verbose=2)
test_error_rate

45/45 - 0s - loss: 0.1459 - acc: 1.0000


[0.14590765800740985, 1.0]

In [18]:
print(
      "{} : {:.2f}%".format(model.metrics_names[1],
              test_error_rate[1]*100))
print(
      "{} : {:.2f}%".format(model.metrics_names[0],
              test_error_rate[0]*100))
#You can run the code again to see how the model perform

acc : 100.00%
loss : 14.59%


### STEP 6 : Prediction 

In [19]:
predicted_targets = model.predict_classes(X_test)
predicted_targets

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0], dtype=int64)

In [20]:
iris_target_array = iris_target_df.values
iris_target_array

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [21]:
target = encoder.fit_transform(iris_target_array)
target

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [22]:
# true_targets = encoder.inverse_transform()
# true_targets
y_test.values

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [23]:
true_targets = encoder.inverse_transform(y_test.values)
true_targets

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [24]:
#performance_tracker(predicted_targets, true_targets)
flowers = {0:'Setosa', 1:'Versicolor', 2:'Virginica'}
print("Flowers in test set: Setosa={} Versicolor={} Virginica={}".format(
            y_test.Setosa.sum(), y_test.Versicolor.sum(),
            y_test.Virginica.sum()))

Flowers in test set: Setosa=19 Versicolor=13 Virginica=13


In [25]:
for act,exp in zip(predicted_targets, true_targets):
        tup = np.where(exp == 1)
        if act != tup[0][0]:
            print("ERROR: {} predicted as {}".format(flowers[tup[0][0]],
                  flowers[act]))
        else:
            print("CORRECT: {} predicted as {}".format(flowers[tup[0][0]],
                  flowers[act]))

CORRECT: Versicolor predicted as Versicolor
CORRECT: Setosa predicted as Setosa
CORRECT: Virginica predicted as Virginica
CORRECT: Versicolor predicted as Versicolor
CORRECT: Versicolor predicted as Versicolor
CORRECT: Setosa predicted as Setosa
CORRECT: Versicolor predicted as Versicolor
CORRECT: Virginica predicted as Virginica
CORRECT: Versicolor predicted as Versicolor
CORRECT: Versicolor predicted as Versicolor
CORRECT: Virginica predicted as Virginica
CORRECT: Setosa predicted as Setosa
CORRECT: Setosa predicted as Setosa
CORRECT: Setosa predicted as Setosa
CORRECT: Setosa predicted as Setosa
CORRECT: Versicolor predicted as Versicolor
CORRECT: Virginica predicted as Virginica
CORRECT: Versicolor predicted as Versicolor
CORRECT: Versicolor predicted as Versicolor
CORRECT: Virginica predicted as Virginica
CORRECT: Setosa predicted as Setosa
CORRECT: Virginica predicted as Virginica
CORRECT: Setosa predicted as Setosa
CORRECT: Virginica predicted as Virginica
CORRECT: Virginica pre